require: rubocop-rails

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'config/**/*.rb'
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'lib/**/*.rake'
    - 'config/**/*.rb'
    - 'node_modules/**/*'

  NewCops: enable
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 20
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Enabled: false
  Exclude:
    - 'spec/**/*.rb'

Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/services/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/BlockDelimiters:
  BracesRequiredMethods: ['expect']

Style/RedundantPercentQ:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/answer.rb'
