require: rubocop-rails

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - !ruby/regexp /old_and_unused\.rb$/

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/BlockDelimiters:
  BracesRequiredMethods: ['expect']

Style/RedundantPercentQ:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Max: 60
