require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*.rb'
    - 'script/**/*.rb'
    - 'node_modules/**/*'
  NewCops: enable
  DisplayCopNames: true
  StyleGuideCopsOnly: false
 
Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 20
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15
  Enabled: false
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/BlockComments:
  Exclude:
    - 'spec/*.rb'

Style/BlockDelimiters:
  BracesRequiredMethods: ['expect']
