require: rubocop-rails

AllCops:
  DisplayCopNames: true
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/BlockDelimiters:
  BracesRequiredMethods: ['expect']

Style/RedundantPercentQ:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Max: 60
