require: rubocop-rails

AllCops:
  DisplayCopNames: true
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
