language: ruby
rvm:
  - 2.7.1

notifications:
  email: false

addons:
  postgresql: "10"

services:
  - redis-server

cache: bundler

before_script:
  - psql -c 'create database qna_test;' -U postgres
  - bundle exec rails db:setup

script:
  - bundle exec rspec --tag ~visual

gemfile:
  - Gemfile
