language: ruby

rvm:
- 2.7.1

addons:
  postgresql: "10"

services:
- redis-server

bundler_args: --jobs=3 --retry=3
cache: bundler

before_script:
- psql -c 'create database qna_test;' -U postgres
- bundle exec rake db:setup RAILS_ENV=test

script:
- bundle exec rspec --tag ~visual
