language: ruby
rvm:
  - 2.7.1

notifications:
  email: false

addons:
  postresql: "10"

services:
  - redis-server

bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_script:
  - psql -c 'create database qna_test;' -U postgres
  - bundle exec rails db:setup

script:
  - bundle exec rspec --tag ~visual

gemfile:
  - Gemfile
