language: ruby
rvm:
- 2.0.0

addons:
  postgresql: '10'
  chrome: stable

services:
  - redis-server

cache: bundler

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - psql -c 'create database qna_test;' -U postgres
  - bundle exec rails db:setup

gemfile:
  - Gemfile
