language: ruby
rvm:
- 2.7.1
notifications:
  email: false
addons:
  postgresql: '10'
services:
- redis-server
bundler_args: --jobs=3 --retry=3
cache: bundler
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database qna_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:setup
script:
- bundle exec rspec --tag ~visual
